### ISSUE TITLE
Optional parameter beginning of url

### ISSUE THREAD

**Issue by Jordy8** [dannyvankooten/AltoRouter#150] opened 2016-06-03 21:42 UTC
Hi, love the Altorouter. I've one question.
This is the way I set the routes:

```
$router->addRoutes(array(
	array( 'GET', '/[lang:language]/', 'handler'), //homepage
	array( 'GET', '/[lang:language]/[a:page]/', 'handler'), //content pages
));
```

So it catches:
- http://www.example.com/en/
- http://www.example.com/en/about/
- http://www.example.com/en/whatever/

I want to catch all the requests without the _lang_ parameter too. That way I can automatically add the language parameter later in my handler function.
- http://www.example.com/
- http://www.example.com/about/
- http://www.example.com/whatever/

How to do that? The optional parameter trick is not working because of the trailing slash:

```
$router->addRoutes(array(
	array( 'GET', '/.[lang:language]?/', 'handler'), //homepage
	array( 'GET', '/.[lang:language]?/[a:page]/', 'handler'), //content pages
));
```

Thanks!

**Comment by koenpunt** [comment] 2016-06-05 17:44
Duplicate of #98

**Closed by koenpunt** 2016-06-05 17:44 UTC
